Repository witseie-elen4010/2024-group-lab-003, pull requests merged in 2024-04, with the labels that each got.

#11 Landing page
  index.js
  package-lock.json
  package.json
  src/routes/blank.txt
  src/routes/mainRoutes.js
  src/views/blank.txt
  src/views/create.html
  src/views/join.html
  src/views/landingPage.html
Labels: user-story, Regular Player, Admin Player

#12 Drawing Feature [ #6 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/6 )
  public/scripts/draw.js
  src/routes/mainRoutes.js
  src/views/drawing.html
Labels: user-story, Regular Player, Admin Player

#13 Create A Room [ #7 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/7 )
  index.js
  package-lock.json
  package.json
  public/scripts/create.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/services/dbSchema.js
  src/views/create.html
Labels: user-story, Admin Player

#14 Join A Room [ #3 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/3 )
  index.js
  public/scripts/blank.txt
  public/scripts/join.js
  public/scripts/waitingRoom.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/routes/mainRoutes.js
  src/services/dbSchema.js
  src/views/join.html
  src/views/landingPage.html
  src/views/waitingRoom.html
Labels: user-story, Regular Player

#15 Waiting Room [ #4 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/4 )
  .github/workflows/playwright.yml
  documentation/ADR/ADRTemplate.md
  documentation/ADR/DatabaseConfiguration.md
  documentation/ADR/blank.txt
  documentation/Conventions/code_review_guide.md
  documentation/Conventions/code_style_guide.md
  index.js
  playwright.config.js
  public/css/blank.txt
  public/css/waitingRoom.css
  public/scripts/create.js
  public/scripts/draw.js
  public/scripts/join.js
  public/scripts/waitingRoom.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/routes/mainRoutes.js
  src/services/blank.txt
  src/services/dbSchema.js
  src/views/create.html
  src/views/join.html
  src/views/waitingRoom.html
  tests/createRoom.spec.ts
  tests/drawing.spec.ts
  tests/landingPage.spec.ts
Labels: user-story, Regular Player, Admin Player

#18 Admin Can Start Game [ #9 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/9 )
  documentation/Conventions/code_style_guide.md
  documentation/Sprints/Sprint_1/ScrumBoardStart.png
  documentation/Sprints/Sprint_1/UserStoryMap.jpg
  package-lock.json
  package.json
  playwright.config.js
  public/scripts/create.js
  public/scripts/join.js
  public/scripts/waitingRoom.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/services/dbSchema.js
  src/views/waitingRoom.html
  tests/createRoom.spec.ts
  tests/drawing.spec.ts
  tests/landingPage.spec.ts
  tests/playerWaitingRoom.spec.ts
Labels: user-story, Regular Player, Admin Player

#26 Azure Config Refactor
  .github/workflows/main_doodlesallthewaydown.yml
  package.json
Labels: enhancement

#27 Save Image [ #23 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/23 )
  public/scripts/draw.js
  src/views/drawing.html
  tests/drawing.spec.ts
Labels: user-story, Regular Player, Admin Player

#28 Leave room [ #19 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/19 )
  public/scripts/waitingRoom.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/views/waitingRoom.html
  tests/leaveRoom.ts
Labels: user-story, Regular Player

#29 Admin can remove a player from the room [ #20 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/20 )
  package.json
  public/scripts/waitingRoom.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  tests/leaveRoom.spec.ts
Labels: user-story, Admin Player

#30 User can be prompted to describe a picture [ #21 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/21 )
  src/routes/mainRoutes.js
  src/views/description.html
  tests/description.spec.ts
Labels: user-story, Regular Player, Admin Player

#31 Begin by drawing in book [ #22 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/22 )
  public/scripts/draw.js
  public/scripts/waitingRoom.js
  src/views/drawing.html
  tests/drawing.spec.ts
Labels: user-story, Regular Player, Admin Player

#32 Undo, Redo and Clear Drawings [ #25 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/25 )
  package-lock.json
  package.json
  public/scripts/draw.js
  src/views/drawing.html
  tests/drawing.spec.ts
Labels: user-story, Regular Player, Admin Player

#33 Color Palette For Drawing [ #24 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/24 )
  public/scripts/draw.js
  src/views/drawing.html
  tests/drawing.spec.ts
Labels: user-story, Regular Player, Admin Player
