Repository witseie-elen4010/2024-group-lab-003, pull requests merged in 2024-05, with the labels that each got.

#44 Time Per Round Added [ #40 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/40)
  public/scripts/waitingRoom.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/services/dbSchema.js
Labels: user-story, Admin Player

#45 Admin Can Cancel a Game [ #42 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/42 )
  package-lock.json
  package.json
  public/scripts/waitingRoom.js
Labels: user-story, Admin Player

#47 System Admin can access log page [ #46 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/46 )
  index.js
  package-lock.json
  package.json
  public/css/landingPage.css
  public/scripts/landingPage.js
  src/views/landingPage.html
Labels: user-story, System Admin

#48 Respond By Drawing [ #36 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/36)
  index.js
  public/scripts/description.js
  public/scripts/draw.js
  public/scripts/waitingRoom.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/services/dbSchema.js
  src/views/description.html
  src/views/drawing.html
  tests/description.spec.ts
  tests/drawing.spec.ts
  tests/leaveRoom.spec.ts
  tests/playerWaitingRoom.spec.ts
Labels: user-story, Regular Player, Admin Player

#55 Added tests for room controller functions
  package-lock.json
  package.json
  test_jest/roomController.test.js
Labels: Tests

#56 View game [ #37 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/37)
  public/css/gameOver.css
  public/scripts/gameOver.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/routes/mainRoutes.js
  src/views/gameOver.html
Labels: user-story, Regular Player, Admin Player

#57 Can Respond With Text [ #35 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/35)
  package-lock.json
  package.json
  public/scripts/description.js
  public/scripts/draw.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/services/dbSchema.js
  src/views/description.html
  src/views/drawing.html
Labels: user-story, Regular Player, Admin Player

#58 View game logs for system admin [ #39 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/39)
  package-lock.json
  public/css/logs.css
  public/scripts/logs.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/routes/mainRoutes.js
  src/views/logs.html
Labels: user-story, System Admin

#60 Player can create Account and Login [ #49 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/49)
  .github/workflows/jest.yml
  .github/workflows/playwright.yml
  index.js
  package-lock.json
  package.json
  public/css/landingPage.css
  public/css/logs.css
  public/images/draw.gif
  src/routes/mainRoutes.js
  src/views/create.ejs
  src/views/error.ejs
  src/views/index.ejs
  src/views/join.ejs
  src/views/landingPage.ejs
  src/views/logs.ejs
  src/views/partials/footer.ejs
  src/views/partials/header.ejs
  src/views/profile.ejs
  src/views/waitingRoom.ejs
  test_jest/auth0.test.js
  test_jest/insertUser.test.js
  tests/Login.spec.ts
  tests/createRoom.spec.ts
  tests/description.spec.ts
  tests/drawing.spec.ts
  tests/landingPage.spec.ts
  tests/leaveRoom.spec.ts
  tests/playerWaitingRoom.spec.ts
Labels: user-story, Regular Player, Admin Player

#62 Improved User Interface (UI) Experience for Creating and Joining a Game
  .github/workflows/jest.yml
  .github/workflows/playwright.yml
  public/css/landingPage.css
  public/css/waitingRoom.css
  src/views/create.ejs
  src/views/description.html
  src/views/join.ejs
  src/views/profile.ejs
  test_jest/auth0.test.js
  test_jest/auth0Integration.test.js
  test_jest/mongoDBIntegration.test.js
  test_jest/roomController.test.js
Labels: user-story, Regular Player, Admin Player

#63 Added pen width [ #54 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/54)
  public/scripts/draw.js
  src/views/drawing.html
Labels: user-story, Regular Player, Admin Player

#64 View Game History [ #53 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/53 )
  public/scripts/draw.js
  public/scripts/gameOver.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/views/gameOver.html
Labels: user-story, Regular Player, Admin Player

#65 As a Player I The game can end for me [ #59 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/59)
  public/css/description.css
  public/css/drawing.css
  public/scripts/description.js
  public/scripts/draw.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/views/description.html
  src/views/drawing.html
Labels: user-story, Regular Player, Admin Player

#66 Loading screens [ #38 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/38)
  public/images/blank.txt
  public/images/roundLoader.gif
  public/scripts/description.js
  public/scripts/draw.js
  public/scripts/waitingRoom.js
  src/views/description.html
Labels: user-story, Regular Player, Admin Player

#67 Added Shapes for Drawing [ #52 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/52)
  public/scripts/draw.js
  src/views/drawing.html
Labels: user-story, Regular Player, Admin Player

#71 System Admin Can View All Logs [ #70 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/70 )
  documentation/ADR/DatabaseConfiguration.md
  documentation/ADR/DateAndTime.md
  documentation/ADR/RoundScheduling.md
  documentation/DesignChoises/DatabaseConfiguration.md
  documentation/DesignChoises/RoundScheduling.md
  public/scripts/logs.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/services/dbSchema.js
  src/views/logs.ejs
  test_jest/mongoDBIntegration.test.js
  test_jest/roomController.test.js
Labels: user-story, System Admin

#72 Remember Me [ #69 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/69)
  public/scripts/create.js
  public/scripts/description.js
  public/scripts/draw.js
  public/scripts/join.js
  public/scripts/landingPage.js
  public/scripts/logs.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/routes/mainRoutes.js
  src/services/dbSchema.js
  src/views/description.html
  src/views/drawing.html
  src/views/gameOver.ejs
  src/views/landingPage.ejs
  src/views/waitingRoom.html
  test_jest/roomController.test.js
Labels: security, user-story, Regular Player, Admin Player

#77 Enhanced UI [ #68 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/68)
  README.md
  documentation/Sprints/Sprint_3/coverage.png
  documentation/Sprints/Sprint_4/UserStoryMap.jpg
  package-lock.json
  package.json
  public/css/about.css
  src/routes/mainRoutes.js
  src/views/about.ejs
  src/views/description.html
  src/views/partials/header.ejs
  src/views/profile.ejs
  test_jest/roomController.test.js
Labels: user-story, Regular Player, Admin Player

#78 As a player I can see the metadata of viewing the game [ #50 ]( https://github.com/witseie-elen4010/2024-group-lab-003/issues/50)
  public/scripts/create.js
  public/scripts/gameOver.js
  public/scripts/join.js
  public/scripts/landingPage.js
  public/scripts/logs.js
  public/scripts/waitingRoom.js
  src/controllers/roomController.js
  src/routes/dbRoutes.js
  src/views/waitingRoom.html
Labels: user-story, Regular Player, Admin Player
